# Generated by Django 3.0.4 on 2020-03-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='title',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='zipcode',
            field=models.CharField(max_length=9),
        ),
    ]
