# Generated by Django 3.0.4 on 2020-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientprofile', '0002_auto_20200315_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
