# Generated by Django 3.0.4 on 2020-03-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientprofile', '0003_auto_20200319_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='newprofile',
            field=models.BooleanField(default=True),
        ),
    ]
