# Generated by Django 3.0.4 on 2020-03-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientprofile', '0005_auto_20200319_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='password',
        ),
    ]
