# Generated by Django 3.0.4 on 2020-03-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientprofile', '0006_remove_clientprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
