# Generated by Django 3.0.4 on 2020-03-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientprofile', '0009_auto_20200326_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='newprofile',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
