# Generated by Django 3.0.4 on 2020-03-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientprofile', '0010_auto_20200327_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='address1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='zipcode',
            field=models.CharField(max_length=9),
        ),
    ]
